### ISSUE TITLE
Derivative in discrete version of state-space definition

### ISSUE THREAD

**Issue by WasabiFan** [calcmogul/state-space-guide#8]
Section 5.3.3, Definition 5.3.1, shows a continuous and discrete version of the same equation:
![image](https://user-images.githubusercontent.com/3310349/62833037-baea8e00-bc6a-11e9-83b8-95c6b405fcf6.png)

In the continuous case, the LHS is the derivative of `x`, but in the discrete case the derivative is dropped and no delta takes its place: the LHS simply reads `x_{k+1}`. Why is this?

**Comment by calcmogul** [comment]
Although it isn't clear from the notation, the continuous and discrete versions have different A, B, C, and D matrices. The discrete equation returns the next state rather than a change in state because while you could have `x_{k+1} - x_k = Ax_k + Bu_k`, you have to do an extra addition to propagate the model forward. Also note that the poles would be given by the eigenvalues of `A + I` rather than the eigenvalues of `A`. I know a mathematics guy that's annoyed by the deviation in notation from the continuous version, but :man_shrugging:. Practicality beats purity in this case.

Section 6.5 "Matrix exponential" through 6.7 go into more detail on what the discrete matrices are, and G.3 "Zero-order hold for state-space" shows a derivation.

**Comment by WasabiFan** [comment]
Thanks for the clarification! I appreciate the quick response. It might be good to have a note about that near the definition.
